env:
  browser: true
  es6: true
  node: true
extends: 
  - airbnb-base
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - vue
  - prettier
rules:
  prettier/prettier: error
  import/no-unresolved: off
  arrow-parens: 
   - error
   - as-needed
